import type { Metadata } from 'next';

import { Geist, Geist_Mono } from 'next/font/google';

import { RootStoreProvider } from '@/lib/store-adapter/store';
import './globals.css';
import { FC, ReactNode } from 'react';

const geistSans = Geist({
  subsets: ['latin'],
  variable: '--font-geist-sans',
});

const geistMono = Geist_Mono({
  subsets: ['latin'],
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: FC<RootLayoutProps> = (props) => {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RootStoreProvider>{props.children}</RootStoreProvider>
      </body>
    </html>
  );
};

export default RootLayout;
