import type { Metadata } from 'next';

import { Geist, Geist_Mono } from 'next/font/google';
import { FC, ReactNode } from 'react';

import './globals.css';

import { AppInitializer } from '@/app/AppInitializer';
import { Toaster } from '@/components/ui/sonner';
import { RootStoreProvider } from '@/lib/stores/rootStore';

const geistSans = Geist({
  subsets: ['latin'],
  variable: '--font-geist-sans',
});

const geistMono = Geist_Mono({
  subsets: ['latin'],
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: FC<RootLayoutProps> = (props) => {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RootStoreProvider>
          <Toaster />
          <AppInitializer>{props.children}</AppInitializer>
        </RootStoreProvider>
      </body>
    </html>
  );
};

export default RootLayout;
